[global.databases.my_pg_db]
url = "postgres://rocket:rocket@localhost:6543/rocket"

## defaults for _all_ profiles
[default]
address = "127.0.0.1"
limits = { form = "64 kB", json = "1 MiB" }


[debug]
port = 8000
## only the `json` key from `default` will be overridden; `form` will remain
limits = { json = "10MiB" }
workers = 16
secret_key = "QTiJBsssymvSdved2Iya8XvxAH8lHQ+u7ikDRK/RJZM="
log_level = "normal"

## set only when compiled in release mode, i.e, `cargo build --release`
[release]
port = 9999
secret_key = "VV2VJqPyv5ryrh0ezD31zJ3o2mNBsgl114Q4GOjGAPs="
